# Generated by Django 3.2.5 on 2021-07-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=20)),
                ('companyaddress', models.CharField(max_length=200)),
                ('contactno', models.IntegerField(max_length=15)),
                ('Contactperson', models.CharField(max_length=20)),
                ('meetingpurpose', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
    ]
